language: java

jdk:
  - openjdk11
  
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   

cache:
  directories:
    - $HOME/.m2/repository

before_cache:
  - rm -R $HOME/.m2/repository/ca/weblite

before_install:
  - openssl aes-256-cbc -K $encrypted_2dffe6d9f24e_key -iv $encrypted_2dffe6d9f24e_iv -in codesigning.asc.enc -out codesigning.asc -d
  - gpg --fast-import codesigning.asc
  - gpg --list-keys
  - cp .travis.settings.xml $HOME/.m2/settings.xml

install: true

script: "mvn -e clean install"

deploy:
  - provider: script
    script: "mvn -e -q -P travis,release -Dmaven.test.skip=true clean deploy"
    skip_cleanup: true
    on:
      branch: develop
      tags: false
  - provider: script
    # add "`git log --pretty=format:'%h' -n 1`" for git commit hash
    script: "mvn -e -P travis,release -Dmaven.test.skip=true clean deploy -Drevision=$TRAVIS_TAG-`date +%Y%m%d`"
    skip_cleanup: true
    on:
      branch: master
      tags: true

notifications:
  email:
    recipients:
      - meister.fuchs@gmail.com
    on_success: change
    on_failure: always
  webhooks:
    urls:
    #  - https://webhooks.gitter.im/e/02860416326b2469fdcc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
